apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-zps3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-zps3@sha256:afbe42db4ee555cac95150a48892fbd118c1b4f4a591202008d24931bcc7e5ca
        name: my-python
        resources: {}
status: {}
